"""advanced_document_features

Revision ID: b68c6b4bb2f6
Revises: 001
Create Date: 2026-03-29 16:19:27.108935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b68c6b4bb2f6'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_folder_id', sa.Integer(), nullable=True),
    sa.Column('default_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_metadata_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['default_folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    op.create_table('document_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_template_versions_id'), 'document_template_versions', ['id'], unique=False)
    op.create_index(op.f('ix_document_template_versions_template_id'), 'document_template_versions', ['template_id'], unique=False)
    op.create_table('document_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uix_user_document_view')
    )
    op.create_index(op.f('ix_document_views_id'), 'document_views', ['id'], unique=False)
    op.create_index('ix_user_last_viewed', 'document_views', ['user_id', 'last_viewed_at'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('document_id IS NOT NULL OR folder_id IS NOT NULL', name='check_doc_or_folder'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uix_user_favorite_document'),
    sa.UniqueConstraint('user_id', 'folder_id', name='uix_user_favorite_folder')
    )
    op.create_index(op.f('ix_user_favorites_document_id'), 'user_favorites', ['document_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_folder_id'), 'user_favorites', ['folder_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_id'), 'user_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('hash_algorithm', sa.String(length=10), server_default='sha256', nullable=True))
    op.add_column('documents', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('expiry_action', sa.String(length=20), server_default='notify', nullable=False))
    op.add_column('documents', sa.Column('expiry_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('archived_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('archive_reason', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('locked_by_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('lock_reason', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['locked_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'lock_reason')
    op.drop_column('documents', 'lock_expires_at')
    op.drop_column('documents', 'locked_at')
    op.drop_column('documents', 'locked_by_id')
    op.drop_column('documents', 'is_locked')
    op.drop_column('documents', 'archive_reason')
    op.drop_column('documents', 'archived_by')
    op.drop_column('documents', 'archived_at')
    op.drop_column('documents', 'is_archived')
    op.drop_column('documents', 'expiry_notified_at')
    op.drop_column('documents', 'expiry_action')
    op.drop_column('documents', 'expires_at')
    op.drop_column('documents', 'hash_algorithm')
    op.drop_column('documents', 'file_hash')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_folder_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_document_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index('ix_user_last_viewed', table_name='document_views')
    op.drop_index(op.f('ix_document_views_id'), table_name='document_views')
    op.drop_table('document_views')
    op.drop_index(op.f('ix_document_template_versions_template_id'), table_name='document_template_versions')
    op.drop_index(op.f('ix_document_template_versions_id'), table_name='document_template_versions')
    op.drop_table('document_template_versions')
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
